#ifndef DEFINITIONS_H_INCLUDED
#define DEFINITIONS_H_INCLUDED

#define NUM_PIECES 6
enum PIECE {
    PAWN=0, ROOK=1, KNIGHT=2, BISHOP=3, QUEEN=4, KING=5
};

#define NUM_COLORS 2
enum COLOR {
    WHITE=0, BLACK=1
};

#endif // DEFINITIONS_H_INCLUDED
