#ifndef PIECES_H_INCLUDED
#define PIECES_H_INCLUDED

#define BITBOARD_COUNT 10
#define BITBOARD_PIECES 6

enum BITBOARDS {
    PAWN=0, ROOK=1, KNIGHT=2, BISHOP=3, QUEEN=4, KING=5,
    WHITE=6, BLACK=7,
    EN_PASSANT_SQUARE=8,
    CASTLE_RIGHTS=9
};

#endif // PIECES_H_INCLUDED
